version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
  - cmd: dotnet restore
build:
  verbosity: minimal
artifacts:
- path: Docpal\bin\Release\netcoreapp2.2
  name: Docpal
only_commits:
  files:
    - Docpal/
    - '*.cs'
    - '*.sln'
    - 'appveyor.yml'